### ISSUE TITLE
Improve the breakdown of how custom Base64 works

### ISSUE THREAD

**Issue by alexandergre** [whiym/fish#1]
Hi, this is not really an issue but more of a suggestion: I've been trying to implement fish in c# and been stuck with the custom base64 implementation until someone sent me the link to the BASE64.md. I implemented encode/decode and the tests passed for the 'qwertyui' (as well as other variants of string less than 9 chars long), but I'm not getting the expected output when using longer strings. Possibly wrong padding is to blame? I would really appreciate another example of how encode/decode works with a longer string (30 chars would be perfect).

Thanks!

**Comment by whiym** [comment]
Hi @alexandergre, glad you found the instructions useful. For encoding 8 bytes are processed at a time and for decoding 12 bytes are processed at a time. So if the inputs are not multiple of those lengths, they must be padded with nulls. That means there isn't really anything to show for a longer example. If you want to encode 30 bytes, it would be 3 lots of 8 bytes, then the last 6 bytes padded.

**Comment by alexandergre** [comment]
Let me show an example, I'm trying to encode ```0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ```, using the provided algorithm description I get ```..ukn/mrzjj/ibzif/eXyhb/aHyg7/6ryf3/2bye//Uz5sR/Qj5rN/M35qJ/IP4pF/Ez4oB/Aj4nx/w3kcS.RmhbO.N6haK.```, however the correct result is 
```RmhbO.N6haK.Aj4nx/w3kcS.IP4pF/Ez4oB/Qj5rN/M35qJ/2bye//Uz5sR/aHyg7/6ryf3/ibzif/eXyhb/..ukn/mrzjj/```. As you can see, the blocks themselves are ok, but they are at incorrect positions. Similarly, when I try to decode the correct result, I get ```UVWXYZ\u0000\u0000MNOPQRSTEFGHIJKLwxyzABCDopqrstuvghijklmn89abcdef01234567```. I tried to fix it by re-positioning the blocks, it worked for the decoding, but if I apply the same to encoding, it works for the above example, but breaks in other cases, for example when using ```qwertyui```. 
Of course, it's possible that my implementation is incorrect, but without an example on encoding/decoding larger strings I'm not sure how to fix it. 
Thank you very much for looking into this!

**Comment by alexandergre** [comment]
Btw, I think the line ```Taking the first 4 bytes (left), reading from the left and shifting to the left to form a 32 bit integer:``` is meant to be ```Taking the first 4 bytes (left), reading from the **right** and shifting to the left to form a 32 bit integer:``` (this is what I do in my implementation)

**Comment by alexandergre** [comment]
I modified my algorithm to work with 8 characters at a time and it's working properly now! Still, I think the algorithm would be easier to understand if the example used a string of, say 16 characters.

**Comment by whiym** [comment]
Glad you got it sorted in the end.

> Btw, I think the line Taking the first 4 bytes (left), reading from the left and shifting to the left to form a 32 bit integer: is meant to be Taking the first 4 bytes (left), reading from the **right** and shifting to the left to form a 32 bit integer: (this is what I do in my implementation)

Actually we're both a bit wrong here. I was trying to explain which bytes get shifted the most to form the 32 bit integer so "reading direction" doesn't really make sense. But, you're right, it's the resulting 32 bit integer that is read from the right. I'll update the docs when I have a moment. Cheers.
